version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: oedipus
      POSTGRES_USER: oedipus
      POSTGRES_PASSWORD: oedipus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oedipus"]
      interval: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
